=== jalyna/oakdex-pokemon/lib/oakdex/pokemon/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "Pokemon",
  "definitions": {
    "ev_stats": {
      "type": "object",
      "properties": {
        "hp": {
          "type": "integer",
          "minimum": 0,
          "maximum": 255
        },
        "atk": {
          "type": "integer",
          "minimum": 0,
          "maximum": 255
        },
        "def": {
          "type": "integer",
          "minimum": 0,
          "maximum": 255
        },
        "sp_atk": {
          "type": "integer",
          "minimum": 0,
          "maximum": 255
        },
        "sp_def": {
          "type": "integer",
          "minimum": 0,
          "maximum": 255
        },
        "speed": {
          "type": "integer",
          "minimum": 0,
          "maximum": 255
        }
      },
      "required": [
        "hp",
        "atk",
        "def",
        "sp_atk",
        "sp_def",
        "speed"
      ],
      "additionalProperties": false
    },
    "iv_stats": {
      "type": "object",
      "properties": {
        "hp": {
          "type": "integer",
          "minimum": 0,
          "maximum": 31
        },
        "atk": {
          "type": "integer",
          "minimum": 0,
          "maximum": 31
        },
        "def": {
          "type": "integer",
          "minimum": 0,
          "maximum": 31
        },
        "sp_atk": {
          "type": "integer",
          "minimum": 0,
          "maximum": 31
        },
        "sp_def": {
          "type": "integer",
          "minimum": 0,
          "maximum": 31
        },
        "speed": {
          "type": "integer",
          "minimum": 0,
          "maximum": 31
        }
      },
      "required": [
        "hp",
        "atk",
        "def",
        "sp_atk",
        "sp_def",
        "speed"
      ],
      "additionalProperties": false
    }
  },
  "properties": {
    "species_id": {
      "type": "string"
    },
    "exp": {
      "type": "integer",
      "minimum": 0,
      "maximum": 1640000
    },
    "gender": {
      "type": "string",
      "enum": [
        "male",
        "female",
        "neuter"
      ]
    },
    "ability_id": {
      "type": "string"
    },
    "item_id": {
      "type": ["string", "null"]
    },
    "nature_id": {
      "type": "string"
    },
    "hp": {
      "type": "integer",
      "minimum": 0,
      "maximum": 10000000
    },
    "friendship": {
      "type": "integer",
      "minimum": 0,
      "maximum": 255
    },
    "original_trainer": {
      "type": ["string", "null"]
    },
    "ev": {
      "$ref": "#/definitions/ev_stats"
    },
    "iv": {
      "$ref": "#/definitions/iv_stats"
    },
    "primary_status_condition": {
      "type": ["string", "null"],
      "enum": [
        "poison",
        "badly_poisoned",
        "paralysis",
        "sleep",
        "freeze",
        "burn",
        null
      ]
    },
    "wild": {
      "type": ["boolean", "null"]
    },
    "moves": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "properties": {
          "move_id": {
            "type": "string"
          },
          "pp": {
            "type": "integer",
            "minimum": 0,
            "maximum": 50
          },
          "max_pp": {
            "type": "integer",
            "minimum": 0,
            "maximum": 50
          }
        },
        "required": [
          "move_id",
          "pp",
          "max_pp"
        ],
        "additionalProperties": false
      }
    },
    "amie": {
      "type": ["object", "null"],
      "properties": {
        "affection": {
          "type": "integer",
          "minimum": 0,
          "maximum": 255
        },
        "fullness": {
          "type": "integer",
          "minimum": 0,
          "maximum": 255
        },
        "enjoyment": {
          "type": "integer",
          "minimum": 0,
          "maximum": 255
        }
      },
      "additionalProperties": false
    },
    "growth_events": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "options": {
            "type": "object"
          }
        },
        "required": [
          "name",
          "options"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "species_id",
    "exp",
    "ability_id",
    "gender",
    "nature_id",
    "hp",
    "iv",
    "ev",
    "moves",
    "friendship"
  ],
  "additionalProperties": false
}

=== jalyna/oakdex-pokemon/spec/fixtures/charmander.json
{
  "exp": 2035,
  "gender": "male",
  "ability_id": "Blaze",
  "nature_id": "Naughty",
  "hp": 39,
  "iv": {
    "hp": 19,
    "atk": 31,
    "def": 1,
    "sp_atk": 13,
    "sp_def": 7,
    "speed": 22
  },
  "ev": {
    "hp": 0,
    "atk": 0,
    "def": 0,
    "sp_atk": 0,
    "sp_def": 0,
    "speed": 0
  },
  "moves": [
    {
      "move_id": "Smokescreen",
      "pp": 20,
      "max_pp": 20
    },
    {
      "move_id": "Growl",
      "pp": 40,
      "max_pp": 40
    },
    {
      "move_id": "Scratch",
      "pp": 35,
      "max_pp": 35
    },
    {
      "move_id": "Ember",
      "pp": 25,
      "max_pp": 25
    }
  ],
  "original_trainer": null,
  "primary_status_condition": null,
  "wild": null,
  "item_id": null,
  "amie": null,
  "friendship": 70,
  "growth_events": [

  ],
  "species_id": "Charmander"
}

=== jalyna/oakdex-pokemon/spec/fixtures/pikachu.json
{
  "exp": 100,
  "gender": "female",
  "ability_id": "Static",
  "nature_id": "Bashful",
  "hp": 12,
  "iv": {
    "hp": 10,
    "atk": 10,
    "def": 10,
    "sp_atk": 10,
    "sp_def": 10,
    "speed": 10
  },
  "ev": {
    "hp": 10,
    "atk": 10,
    "def": 10,
    "sp_atk": 10,
    "sp_def": 10,
    "speed": 10
  },
  "moves": [
    {
      "move_id": "Thunder Shock",
      "pp": 30,
      "max_pp": 40
    }
  ],
  "friendship": 70,
  "growth_events": [

  ],
  "species_id": "Pikachu"
}
